### ISSUE TITLE
Add an option to show elapsed time instead of remaining time

### ISSUE THREAD

**Issue by papin97** [NaamloosDT/foo_discord#10]
I prefer showing elapsed time on my Discord Rich Presence rather than remaining time.
Currently, I can't find the toggle in your component's setting.
Implement the toggle pls.
Thanks.

**Comment by Naamloos** [comment]
On it.

**Comment by Naamloos** [comment]
![](https://saiko.is-a-good-waifu.com/2647aa.png)
Comin up!
Pushing it in a sec, build coming a bit later

**Comment by 0x263b** [comment]
Is this in 1.8?
