### ISSUE TITLE
Show Album art on logo in discord

### ISSUE THREAD

**Issue by avolden** [NaamloosDT/foo_discord#12]
Is it possible to show the album art of the track played in discord instead of a simple logo ?

**Comment by thxne** [comment]
This would be super cool if possible

**Comment by Naamloos** [comment]
t h a t
i s
n o t
p o s s i b l e

**Comment by Naamloos** [comment]
https://github.com/NaamloosDT/foo_discord/wiki/Frequently-Asked-Questions#does-this-support-album-art
