### ISSUE TITLE
Appearance is not consistent

### ISSUE THREAD

**Issue by atakhmaz** [NaamloosDT/foo_discord#13]
So I just started using this and I have to say its awesome however I noticed that it will alternate between two different appearances when using it. Here are the two appearances I am talking about: 
![1](https://user-images.githubusercontent.com/21162253/43363048-0d5ec056-92b0-11e8-808b-32e464787be1.png)
![2](https://user-images.githubusercontent.com/21162253/43363049-0ec838f0-92b0-11e8-97d0-6ee24849f131.png)
It seems to be completely random and I cant get it to stick to one.

ALSO, it seems that foobar has two types of artists fields: Album Artist and Artist Name. Is there a way that you can make it so it choose either one because some of my songs don't have Artist Names and instead have Album Artists and it doesn't end up showing on Discord. Thanks a lot for this.

**Comment by Naamloos** [comment]
👌

**Comment by Naamloos** [comment]
I don't know about the art inconsistencies though

**Comment by Naamloos** [comment]
I'll likely call it "prefer album artist" / "prefer song artist" and make it automatically pick the other when one's empty

**Comment by Naamloos** [comment]
Oops, that's the other foobar addon, I didn't make that one.. Mine has no such issue 🤣
