### ISSUE TITLE
Feature request: Remove status when stopped.

### ISSUE THREAD

**Issue by Drraze** [NaamloosDT/foo_discord#14]
Would it be possible to add on option for the rich presence to stop showing on Discord when music is stopped? Right now only way to remove it is to close foobar, if you launch any game, foobar stays as the visible thing, even while stopped.
This way, rich presence would only be shown when music is actually playing or is paused, without needing to close the program entirely to remove it.
Thanks.

**Comment by Naamloos** [comment]
Pretty sure I already implemented this
