### ISSUE TITLE
Use "Listening to" instead of "Playing a game"

### ISSUE THREAD

**Issue by Radiant-Xyz** [NaamloosDT/foo_discord#17]
foobar2000 isn't a game and I'd prefer it to be displayed in Discord properly as a music player by changing the rich presence information from "Playing a game" to "Listening to" if possible. I saw a few bots using this "mode" and I think it would be most fitting in this case here.

**Comment by Naamloos** [comment]
Not possible with the current api. Spotify is a special case

**Comment by Naamloos** [comment]
And yes, bots CAN use it. User apps can't

**Comment by Radiant-Xyz** [comment]
Sad to hear that, but thanks for clearing that up.
