### ISSUE TITLE
Request: Use album artwork as image

### ISSUE THREAD

**Issue by tecosaur** [NaamloosDT/foo_discord#19]
Basically what the title is. It would be cool if the image used could be the album art if available, instead of the foobar2k icon.

**Comment by Naamloos** [comment]
https://github.com/NaamloosDT/foo_discord/wiki/Frequently-Asked-Questions#does-this-support-album-art

**Comment by tecosaur** [comment]
Aaah, sorry for not reading the Q&A. Thanks.
