### ISSUE TITLE
Cover pictures instead foobar logo

### ISSUE THREAD

**Issue by RadegasTCZ** [NaamloosDT/foo_discord#20]
Can you add ability to show Cover picture tag from a audio file instead of foobar logo when the file contains one? There is an example file with Cover picture. :)
![image](https://user-images.githubusercontent.com/22341950/45097088-505bd480-b122-11e8-9a0b-f7b571df6444.png)

**Comment by Naamloos** [comment]
invalid
https://github.com/NaamloosDT/foo_discord/wiki/Frequently-Asked-Questions#does-this-support-album-art
