### ISSUE TITLE
Discord listening to activity

### ISSUE THREAD

**Issue by ghost** [NaamloosDT/foo_discord#21]
So apparently you can set your activity to Listening to instead of playing, would be a neat option.

![example](https://user-images.githubusercontent.com/31040099/45114871-7bf4b400-b14e-11e8-9900-289d5d5a00f5.png)

**Comment by Naamloos** [comment]
Invalid as well
https://github.com/NaamloosDT/foo_discord/wiki/Frequently-Asked-Questions#can-you-change-playing-foobar2000-to-listening-to-foobar2000
