### ISSUE TITLE
Custom Icons

### ISSUE THREAD

**Issue by windowslogic** [NaamloosDT/foo_discord#23]
It would be a great idea if we could choose custom pictures for the rich presence.

**Comment by Naamloos** [comment]
go to the wiki / FAQ

**Comment by ghost** [comment]
> 
> 
> go to the wiki / FAQ

The FAQ says that it doesn't support album art, but not custom images...
It would be useful if we could use our own images.

**Comment by Naamloos** [comment]
oh right, still, it's a feature request I'll have to figure out as image opening will _not_ work

**Comment by ghost** [comment]
> 
> 
> oh right, still, it's a feature request I'll have to figure out as image opening will _not_ work

It's okay, maybe you can make this work if we could add an URL of an image?

**Comment by Naamloos** [comment]
no, that won't work
