### ISSUE TITLE
foobar2000 crashes when Discord is not launched.

### ISSUE THREAD

**Issue by ghost** [NaamloosDT/foo_discord#3]
Basically the title. Every time you launch foobar, it'll always crash unless the Discord client is open before foobar. I don't always leave Discord running.
I've attached a crash log, they're pretty much identical to one another each time I launch foobar.
[failure_00000010.txt](https://github.com/NaamloosDT/foo_discord/files/2051352/failure_00000010.txt)

**Comment by Naamloos** [comment]
Ah, I think I can resolve this issue.

I'll look into it tomorrow. Thanks for reporting!

**Comment by Naamloos** [comment]
I can't seem to replicate this bug. The addon seems to just work when my discord isn't running.

Can you try:
- Updating to the latest stable release of foobar2000
- Try the newest release of the addon

Newest release is found here:
https://github.com/NaamloosDT/foo_discord/releases/tag/1.7

Please report back when possible c:

**Comment by Naamloos** [comment]
Also, which OS are you running?

**Comment by Naamloos** [comment]
nvm, that info is in the crash logs

**Comment by ghost** [comment]
I can no longer replicate the crash with the newest revision. However now, it seems the playback info is incorrect now. This fixes itself after pausing multiple times though.

![image](https://user-images.githubusercontent.com/19507841/40845428-f7893d86-65b6-11e8-8f35-e9308406779a.png)
When playback is stopped upon launching

![image](https://user-images.githubusercontent.com/19507841/40845524-43300e4a-65b7-11e8-85e3-772ead548617.png)
When playing

After pausing and playing one more time, playback state is corrected.

Edit: Discord also does not recognize rich presence if I start Discord after starting Foobar (though I think this issue relies on discord itself, since this happens with many other rich presence-enabled apps and games too, yet not all). Naturally, this is resolved by restarting foobar.

**Comment by Reboot80** [comment]
I can no longer replicate the crash with the newest revision. However now, it seems the playback info is incorrect now. This fixes itself after pausing multiple times though.

![image](https://user-images.githubusercontent.com/19507841/40845428-f7893d86-65b6-11e8-8f35-e9308406779a.png)
When playback is stopped upon launching

![image](https://user-images.githubusercontent.com/19507841/40845524-43300e4a-65b7-11e8-85e3-772ead548617.png)
When playing

After pausing and playing one more time, playback state is corrected.

Edit:

**Comment by ghost** [comment]
Update: having crashes again. This seems to only happen under the following conditions:

- Save playback state upon closing Foobar is enabled
- Foobar is currently playing a track
- Either by closing foobar, or having your system restart

It ends up crashing continuously until I remove the plugin. I do hear a bit of the song playback when Foobar launches, only for it to crash a brief moment later.
[failure_00000012.txt](https://github.com/NaamloosDT/foo_discord/files/2063586/failure_00000012.txt)

**Comment by Naamloos** [comment]
THe playback info being incorrect is likely because discord doesn't update presences right away. It should fix itself after a couple of secs anyway. As for the other bug, I'll have to investigate some more

**Comment by Naamloos** [comment]
@Reboot80 are you saving playback state via a different component?

**Comment by Naamloos** [comment]
nvm, I'll check it out. I might know something

**Comment by Naamloos** [comment]
Yesh, I was able to reproduce the bug. I'll get to work right now.

**Comment by Naamloos** [comment]
All right. Latest release should fix it.
https://github.com/NaamloosDT/foo_discord/releases/tag/1.8
@Reboot80

**Comment by ghost** [comment]
I no longer have this issue. Thanks for helping me out.

**Comment by Reboot80** [comment]
I no longer have this issue. Thanks for helping me out.
