### ISSUE TITLE
Overwrites currently playing game when manually switching track

### ISSUE THREAD

**Issue by ghost** [NaamloosDT/foo_discord#4]
When you are playing an actual game and manually switch a track, your status is changed to foobar again, but returns to the game you were playing after a while, however the playing length timer for the game is reset as if it had just been launched.

This does not seem to happen when songs are playing automatically, only when you manually skip or select a new track.

I suggest an option to disable sharing foobar status if you are already playing something else.

**Comment by Naamloos** [comment]
I'll add an option to completely disable rich presences soon 👍

**Comment by Naamloos** [comment]
@fncombo Implemented in latest release (1.7)

https://github.com/NaamloosDT/foo_discord/releases/tag/1.7
