### ISSUE TITLE
Doesn't work when playing from internet radio stream

### ISSUE THREAD

**Issue by Monkeyfume** [NaamloosDT/foo_discord#6]
https://i.imgur.com/6Ql0k7j.png

As you can see here, I'm using foobar2000 to play from an internet radio stream and foo_discord isn't picking it up. I've tried several stations and experienced the same or a similar issue every time. Sometimes, foo_discord just says "00:00 left" (as in the screenshot) and sometimes it says "no name" underneath "foobar2000" and "00:00 left" underneath that.

Tested in screenshot with the following URL:
http://playerservices.streamtheworld.com/api/livestream-redirect/RADIO10AAC.aac

**Comment by Naamloos** [comment]
The plugin is really not intended for internet radios. Afaik those don't have any metadata on artists and song name
